x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: '1.21.7'
  publishedVersionMetadata:
    releaseNote: >-
      HashiCorp Consul Enterprise 1.21.7 for GCP Marketplace.
      Includes Go 1.25.4 security update and Raft integrated storage.
    releaseTypes:
      - Feature
    recommended: true

  # Partner and product identifiers (must match Partner Portal)
  partnerId: 0014M00001h317WQAQ
  solutionId: consul

  images:
    consul:
      properties:
        imageConsul:
          type: FULL
    ubbagent:
      properties:
        imageUbbagent:
          type: FULL

  clusterConstraints:
    resources:
      - replicas: 3
        requests:
          cpu: 500m
          memory: 512Mi
        affinity:
          simpleNodeAffinity:
            type: REQUIRE_ONE_NODE_PER_REPLICA
    k8sVersion: ">=1.21.0"

properties:
  name:
    type: string
    default: consul-test
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE

  # Consul Configuration
  replicas:
    type: integer
    title: Server Replicas
    description: Number of Consul server replicas
    default: 3
    minimum: 1
    maximum: 7

  datacenter:
    type: string
    title: Datacenter Name
    description: Name of the Consul datacenter
    default: dc1

  enableUI:
    type: boolean
    title: Enable Consul UI
    description: Enable the Consul web UI
    default: true

  enableConnect:
    type: boolean
    title: Enable Consul Connect
    description: Enable Consul Connect service mesh
    default: true

  # Storage Configuration
  storageClass:
    type: string
    title: Storage Class
    description: Kubernetes storage class for persistent volumes
    default: standard
    x-google-marketplace:
      type: STORAGE_CLASS
      storageClass:
        type: SSD

  storageSize:
    type: string
    title: Storage Size
    description: Size of persistent volume for each Consul server
    default: "10Gi"

  # Enterprise License (test placeholder)
  consulLicense:
    type: string
    title: Consul Enterprise License
    description: HashiCorp Consul Enterprise license key
    default: "02MV4UU43BK5HGYYTOJZWFQMTMNNEWU33JJ5LUSMSONJFG2TSUKF2E2RCNO5HEGMBSLFLUSMCMK5HGWTL2MN2E6RC2NVGVIZ3ZJZKFK522NJLGWSLJO5UVSM2WPJSEOOLULJMEUZTBK5IWST3JJF3U26SRPFHUOWTMLFUTA6SNK5IXQTCXKV3U6V2NORMWU3DIJVJTA6CNIRUGQT2XKE2U2VCBGJHVIQLJJRBUU4DCNZHDAWKXPBZVSWCSOBRDENLGMFLVC2KPNFEXCSLJO5UWCWCOPJSFOVTGMRDWY5C2KNETMSLKJF3U22SVORGVISLUJVKFMVKNNJGTMTSEIU3E26SROVHUISJVJZCFKM2PIRCXSV3JJFZUS3SOGBMVQSRQLAZVE4DCK5KWST3JJF4U2RCJGFGFIRLZJRKEKMKWIRAXOT3KIF3U62SBO5LWSSLTJFWVMNDDI5WHSWKYKJYGEMRVMZSEO3DULJJUSNSJNJEXOTLKLF2E2RCNORGXURSVJVCECNSNIRATMTKEIJQUS2LXNFSEOVTZMJLWY5KZLBJHAYRSGVTGIR3MORNFGSJWJFVES52NNJMXITKEJV2E26SGKVGUIQJWJVCECNSNIRBGCSLJO5UWGSCKOZNEQVTKMRBUSNSJNVHHMYTOJYYWEQ2JONEW2WTTLFLWI6SJNJYDOSLNGF3FUSCWONNFQTLJJ5WHG2K2GJ4HMWLNIZZUYWC2OBRTE3DJMFLXQ4DEJBVXIY3NHEYWIR3MOVNHSML2LEZEM422KNEXGSLNMR3GI3KWPFRG2RTVLEZFK5DDI44XGYKXJY2US3BRHFTFCPJ5FZWEC5JQGVVW2TLYLEZUYQKMNVJXQQLYNFIVU33LIZHUO5TDLBZTM6RYKZGDA6DKJZRUKVDIKVAXMR3YK4YXM6SYOVVU6TJUOZZVG3LXNVBEK33TOJEHOWDUKEYE642FGM2HAUCHINFDCZCBNNRWCNDEKYYDGMZYKB3W2VTMMF3EUUBUOBFHQSKJHFCDMVKGJRKWCVSQNJVVOSTUMNCDM4DBNQ3G6T3GI5XEWMT2KBFUUUTNI5EFMM3FLJ3XCRTFFNXTO2ZPOMVUCVCONBIFUZ2TF5FVMWLHF5FSW3CHKB3UYN3KIJ4ESN2HJ5QWWNSVMFUWCSDPMVVTAUSUN43TERCRHU6Q"
    x-google-marketplace:
      type: MASKED_FIELD

  # GCP Marketplace Requirements
  consulServiceAccount:
    type: string
    title: Service Account
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >-
          Service account for Consul pods
        roles:
          - type: ClusterRole
            rulesType: CUSTOM
            rules:
              - apiGroups: [""]
                resources: ["pods"]
                verbs: ["get", "list", "watch"]

  reportingSecret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET

required:
  - name
  - namespace
  - replicas
  - datacenter
  - storageClass
  - storageSize
  - consulServiceAccount
  - reportingSecret
