# apptest/deployer/schema.yaml

x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  testingConstraints:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi

properties:
  name:
    type: string
    default: vault-test
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE

  # Override replicas for testing - single node simplifies init/unseal
  replicas:
    type: integer
    default: 1

  storageClass:
    type: string
    title: Storage Class
    description: Storage class for Vault data persistence
    default: standard
    x-google-marketplace:
      type: STORAGE_CLASS
      storageClass:
        type: SSD

  storageSize:
    type: string
    title: Storage Size
    description: Size of persistent volume for each Vault pod
    default: "10Gi"

  # Vault Enterprise license (test default; overridden by validate-marketplace.sh when .hclic is present)
  vaultLicense:
    type: string
    title: Vault Enterprise License
    description: Vault Enterprise license string (contents of your .hclic file)
    default: "02MV4UU43BK5HGYYTOJZWFQMTMNNEWU33JJ5LVU2S2NVLGUTKUNN2FU3KZGVNGSMDXLJLUU3KMK5NGYWTKM52FS2TDPBHHUY3ZJ5CFCMKZKRVTGSLJO5UVSM2WPJSEOOLULJMEUZTBK5IWST3JJF3U26SRPFHUOWTMLFUTA6SNK5IXQTCXKV3U6V2NORMWU3DIJVJTA6CNIRUGQT2XKE2U2VCBGJHVIQLJJRBUU4DCNZHDAWKXPBZVSWCSOBRDENLGMFLVC2KPNFEXCSLJO5UWCWCOPJSFOVTGMRDWY5C2KNETMSLKJF3U22SVORGVISLUJVKFMVKNNJGTMTSEJU3E2VCZOVGXUQLZJVVGO6CNKRRXSV3JJFZUS3SOGBMVQSRQLAZVE4DCK5KWST3JJF4U2RCJGFGFIRLZJRKEKMKWIRAXOT3KIF3U62SBO5LWSSLTJFWVMNDDI5WHSWKYKJYGEMRVMZSEO3DULJJUSNSJNJEXOTLKLF2E2RCNORGXURSVJVCECNSNIRATMTKEIJQUS2LXNFSEOVTZMJLWY5KZLBJHAYRSGVTGIR3MORNFGSJWJFVES52NNJMXITKEJV2E26SGKVGUIQJWJVCECNSNIRBGCSLJO5UWGSCKOZNEQVTKMRBUSNSJNZNGQZCXPAYES2LXNFNG26DILIZU22KPNZZWSYSXHFVWIV3YNRRXSSJWK54UU5DEK54DAYKTGFVVS6JRPJMTERTTLJJUS42JNVSHMZDNKZ4WE3KGOVMTEVLUMNDTS43BK5HDKSLJO5UVSV2SGJMVONLKLJLVC5C2I5DDAWKTGF3WG3JZGBNFOTRQMFLTS5KJNF3WSWKXKIZFSVZVNJNFOULULJDUMMCZKMYXOY3NHEYFUV2OGBQVOOLVJRMFE6KZK42XUWTNHF4WEU2JONEW2RTLMRWUM5KZGJLGWTCXKJUGIR2FORRUQSTWMRDVM2TEI5WHMYTJGFZFUWDLORRFORTVLFLWI3DCK5LHKZCDJJSGMWBQHUXGO3DKOJRW62JZLFGTOZKPMFVTCYRPMFRHK43SKVJTSRKGFNKXOUDHNVKHI2SKLJ3FIOLLIZKSW4RWKFEEES2FJZJEGQJZINBDEK3GLFVE44DMGJWGE4KBOJ5GCT3INE2HSWDQNRATKMLEIFVWGYJUMRLDAMZTHBIHO3KWNRQXMSSQGRYEU6CJJE4UINSVIZGFKYKWKBVGWV2KORRUINTQMFWDM32PMZDW4SZSPJIEWSSSNVDUQVRTMVNHO4KGMUVW6N3LF5ZSWQKUJZUFAWTHKMXUWVSZM4XUWK3MI5IHOTBXNJBHQSJXI5HWC2ZWKVQWSYKIN5SWWMCSKRXTOMSEKE6T2"
    x-google-marketplace:
      type: MASKED_FIELD
