x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: '1.1.3'
  publishedVersionMetadata:
    releaseNote: "Terraform Enterprise for GCP Marketplace"
    releaseTypes:
    - Feature
    recommended: true
  partnerId: hashicorp
  solutionId: terraform-enterprise

  clusterConstraints:
    resources:
    - replicas: 1
      requests:
        cpu: 2000m
        memory: 4Gi

  images:
    '':
      properties:
        tfeImage:
          type: FULL
    ubbagent:
      properties:
        ubbagentImage:
          type: FULL

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME

  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE

  # ---------------------------------------------------------------------------
  # Infrastructure (pre-provisioned via Terraform)
  # Use: cd terraform && terraform apply -var-file=marketplace_test.tfvars
  # ---------------------------------------------------------------------------

  databaseHost:
    type: string
    title: Database Host
    description: "Cloud SQL PostgreSQL private IP address"

  databaseName:
    type: string
    title: Database Name
    default: "tfe"

  databaseUser:
    type: string
    title: Database User
    default: "tfe"

  databasePassword:
    type: string
    title: Database Password
    description: "PostgreSQL password for TFE user"
    x-google-marketplace:
      type: MASKED_FIELD

  redisHost:
    type: string
    title: Redis Host
    description: "Memorystore Redis host:port (e.g., 10.0.0.5:6379)"

  redisPassword:
    type: string
    title: Redis Auth String
    description: "Memorystore Redis AUTH string"
    x-google-marketplace:
      type: MASKED_FIELD

  objectStorageBucket:
    type: string
    title: GCS Bucket Name
    description: "GCS bucket for TFE object storage"

  objectStorageProject:
    type: string
    title: GCP Project ID (Storage)
    description: "GCP project ID where the GCS bucket resides"

  # ---------------------------------------------------------------------------
  # TFE Configuration
  # ---------------------------------------------------------------------------

  hostname:
    type: string
    title: TFE Hostname (FQDN)
    description: "Fully qualified domain name for TFE (e.g., tfe.example.com)"

  tfeLicense:
    type: string
    title: TFE License (base64)
    description: "Base64-encoded TFE license file content"
    x-google-marketplace:
      type: MASKED_FIELD

  encryptionPassword:
    type: string
    title: Encryption Password
    description: "Encryption password for TFE data (minimum 16 characters)"
    x-google-marketplace:
      type: MASKED_FIELD

  # ---------------------------------------------------------------------------
  # TLS Certificates (base64-encoded)
  # ---------------------------------------------------------------------------

  tlsCertificate:
    type: string
    title: TLS Certificate (base64)
    description: "Base64-encoded TLS certificate (PEM format)"
    x-google-marketplace:
      type: MASKED_FIELD

  tlsPrivateKey:
    type: string
    title: TLS Private Key (base64)
    description: "Base64-encoded TLS private key (PEM format)"
    x-google-marketplace:
      type: MASKED_FIELD

  tlsCACertificate:
    type: string
    title: CA Certificate (base64)
    description: "Base64-encoded CA certificate bundle (PEM format)"
    x-google-marketplace:
      type: MASKED_FIELD

  # ---------------------------------------------------------------------------
  # Service Account for Workload Identity
  # ---------------------------------------------------------------------------

  tfeServiceAccount:
    type: string
    title: TFE Service Account
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: "TFE service account for GCS access via Workload Identity"
        roles:
        - type: Role
          rulesType: CUSTOM
          rules:
          - apiGroups: ['']
            resources: ['secrets', 'configmaps']
            verbs: ['get', 'list', 'watch', 'create', 'update', 'delete']

  # ---------------------------------------------------------------------------
  # Billing / Reporting
  # ---------------------------------------------------------------------------

  reportingSecret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET

required:
  - name
  - namespace
  - databaseHost
  - databasePassword
  - redisHost
  - objectStorageBucket
  - objectStorageProject
  - hostname
  - tfeLicense
  - encryptionPassword
  - tlsCertificate
  - tlsPrivateKey
  - tlsCACertificate
  - reportingSecret
