# schema.yaml - Image URI mapping for GCP Marketplace Terraform K8s App
# Reference: https://github.com/GoogleCloudPlatform/marketplace-tools/blob/master/docs/terraform-k8s-app/terraform-k8s-app-packaging-guide.md
#
# This maps Docker image URIs to Terraform variables.
# GCP Marketplace automatically replaces these variables with the published image URIs.

images:
  tfe:
    variables:
      tfe_image_repo:
        type: REPO_WITH_REGISTRY_WITH_NAME
      tfe_image_tag:
        type: TAG
  ubbagent:
    variables:
      ubbagent_image_repo:
        type: REPO_WITH_REGISTRY_WITH_NAME
      ubbagent_image_tag:
        type: TAG
